FROM alpine:3
COPY entrypoint.sh /entrypoint.sh
RUN apk add --no-cache nodejs npm python3 py3-pip && \
  npm install -g pyright && \
  install -d -o nobody /code /.local && chmod +x /entrypoint.sh
# Also add the C stuff for c extensions
RUN apk add --no-cache python3-dev build-base
USER nobody
WORKDIR /code
ENTRYPOINT ["/entrypoint.sh"]
