name: Docker

on:
  push:
    branches: [master]
    tags: ["v*"]
  pull_request:
    branches: [master]
    tags: ["v*"]

jobs:
  publish:
    name: Publish Docker Image
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: dafnifacility/pyright-docker/pyright-slim

        push: ${{ github.event_name != 'pull_request' }}
        tags: latest
        tag_with_ref: true
        labels: |
          org.opencontainers.image.source=${{ github.event.repository.clone_url }}
          org.opencontainers.image.revision=${{ github.sha }}
    - uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: dafnifacility/pyright-docker/pyright
        push: ${{ github.event_name != 'pull_request' }}
        tags: latest
        tag_with_ref: true
        dockerfile: ./Dockerfile-gcc
        labels: |
          org.opencontainers.image.source=${{ github.event.repository.clone_url }}
          org.opencontainers.image.revision=${{ github.sha }}
