name: Docker

on:
  push:
    branches: [master]
    tags: ["v*"]
  pull_request:
    branches: [master]
    tags: ["v*"]

jobs:
  publish-fat:
    name: Publish Fat Docker Image
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
    - name: Build "fat" image
      uses: docker/build-push-action@v5
      with:
        push: ${{ github.event_name != 'pull_request' }}
        tags: dafnifacility/pyright-docker/pyright:latest
        dockerfile: ./Dockerfile-gcc
        labels: |
          org.opencontainers.image.source=${{ github.event.repository.clone_url }}
          org.opencontainers.image.revision=${{ github.sha }}
  publish-slim:
    name: Publish Slim Docker Image
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
    - name: Build "slim" image
      uses: docker/build-push-action@v5
      with:
        push: ${{ github.event_name != 'pull_request' }}
        tags:  dafnifacility/pyright-docker/pyright-slim:latest
        labels: |
          org.opencontainers.image.source=${{ github.event.repository.clone_url }}
          org.opencontainers.image.revision=${{ github.sha }}
